[package]
name = "th"
version = "0.1.0"
authors = ["Kiëd Llaentenn <kiedtl@tilde.team>"]
edition = "2018"

[dependencies]
doryen-fov = "*"
backtrace = "0.3"
ron = "0.6"
serde = "1.0"

[dependencies.termbox-sys]
path = "../termbox"

[dependencies.lib]
path = "../lib"
