# vim: ts=4 sts=4 sw=4 expandtab

[dungeon_info]
layers = [
    [
        contained_levels = 2
        dimensions = [205, 66]
        algorithm = [
            name = "drunk"
            center_weight = 0.1
            previous_direction_weight = 0.65
            max_iterations = 5000
        ]
    ],

    [
        contained_levels = 2
        dimensions = [100, 50]
        algorithm = [
            name = "cellular"
            open_space_percentage = 67
            wall_requirement = 5
            island_requirement = 1
            jobs = [
                [
                    type = "randomfill"
                    repeat = 1
                ],

                [
                    type = "floorbar"
                    height = 1
                    repeat = 1
                ],

                [
                    type = "generation"
                    allow_islands = true
                    repeat = 3
                ],

                [
                    type = "generation"
                    allow_islands = false
                    repeat = 3
                ]
            ]
        ]
    ]
]
